name: Build and Publish Blog

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'        

      - name: Install emacs
        run: |
          sudo apt-get install emacs
          mkdir ~/.emacs.d && touch ~/.emacs.d/init.el

      - name: Install ox-hugo and generate content
        run: |
          emacs --batch --eval "(progn
          (require 'package)
          (add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)
          (package-initialize)
          (package-refresh-contents)
          (package-install 'ox-hugo)
          (require 'ox-hugo)
          (dolist (file (directory-files-recursively \"./entries\" \"\\.org$\"))
                    (with-current-buffer (find-file-noselect file)
                      (org-hugo-export-wim-to-md))))"

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Install hugo
        run: |
          CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@latest    

      - name: Build blog
        run: |
          export PATH=$PATH:~/go/bin
          cd blog && hugo

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./blog/public
  
  deploy:    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
